### ISSUE TITLE
Constrainted generics for higher perfromance

### ISSUE THREAD

**Issue by dzmitry-lahoda** [invertedtomato/integer-compression#12]
May consider replace

```
public override void EncodeMany(IByteWriter stream, UInt64[] values, Int32 offset, Int32 count)
```
with

```
public override void EncodeMany<T>(T stream, UInt64[] values, Int32 offset, Int32 count)
where T:IByteWriter 
```

It may improve performance.

https://github.com/invertedtomato/integer-compression/blob/8b0b80f1e74340b90cc9726c1bf944dbca93b24d/Library/Compression/Integers/Wave3/FibonacciCodec.cs#L37

**Comment by invertedtomato** [comment]
Hey Dzimitry, do you have any performance benchmarks for this kind of optimization? I would have expected them to be similar!

**Comment by dzmitry-lahoda** [comment]
I will recheck my memory regarding this case. May be I over complicate. Also I dislike override. Will test both item.

**Comment by invertedtomato** [comment]
I'm not too much of a fan of override myself, but it does seem to be the right tool in this case.

**Comment by dzmitry-lahoda** [comment]
will check this today to benchmarks.
