### ISSUE TITLE
{Readonly}Span/Memory usage in API? 

### ISSUE THREAD

**Issue by dzmitry-lahoda** [invertedtomato/integer-compression#3]

**Comment by invertedtomato** [comment]
I've had a look into Span/Memory. In this particular case, they offer no performance advantage over a Byte array - actually the opposite - a slight performance decrease.

**Comment by dzmitry-lahoda** [comment]
.NET Core 3 has optimization for Spans. Specifically, it can inline ReadOnlySpans.

**Comment by dzmitry-lahoda** [comment]
I have replaced uint array with custom wrapper and it works well (kind of less than 1% or less perf degradation)[1]

But I guess for byte array backed storage it would be up to 5%.[2]

[1] https://github.com/dzmitry-lahoda/NetStack/blob/4b750853edb6e4fa28d2d23b7fc22fe55bc2f702/Assets/Scripts/src/NetStack.Serialization/BitBuffer.cs#L49

[2] https://github.com/dotnet/coreclr/issues/23620#issuecomment-486982204
