### ISSUE TITLE
Separate method Fibonacci

### ISSUE THREAD

**Issue by dzmitry-lahoda** [invertedtomato/integer-compression#5]
https://github.com/invertedtomato/integer-compression/blob/8b0b80f1e74340b90cc9726c1bf944dbca93b24d/Library/Compression/Integers/Wave3/FibonacciCodec.cs#L76

As I understand I can encode single number via Fibonacci? Could you split it into separate class? I would like that any encoder which does not relies on range of value could be used without reliance on custom writer-reader-buffer-steam.

Same for read https://github.com/invertedtomato/integer-compression/blob/8b0b80f1e74340b90cc9726c1bf944dbca93b24d/Library/Compression/Integers/Wave3/FibonacciCodec.cs#L166

**Comment by dzmitry-lahoda** [comment]
Seems none of codes uses several values to improve coding, so may create spearae nuget for coding single value to increase reuse changes. I.e. i do not need bit-byte-reader-writer. I has my own.

**Comment by dzmitry-lahoda** [comment]
Seems method will loose performance.

**Comment by invertedtomato** [comment]
Thanks for checking!
