### ISSUE TITLE
Would you accept comprison tests

### ISSUE THREAD

**Issue by dzmitry-lahoda** [invertedtomato/integer-compression#9]
https://github.com/invertedtomato/integer-compression#elias-omega

States that is good for under 8 values, but on graph fibonacci seems better. 

Would you accept test showing when one codec is strictly better than other? I like to compare fibonacci  thomson and elias omega. I.e. when we define in game limits for values, I can use different codec depending on limits.

**Comment by invertedtomato** [comment]
I agree. I meant not to say that it was the best for <8, but it does OK. Whilst an interesting algorithm, I wouldn't use Elias-Omega for anything practical!
